# Generated by Django 2.2.10 on 2020-10-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(editable=False, verbose_name='Дата публикации'),
        ),
    ]
