# Generated by Django 2.2.10 on 2020-10-23 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0003_question_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('TE', 'Текстовый ответ'), ('CH', 'Выбор ответа'), ('MU', 'Выбор нескольких ответов')], default='TE', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 0, 49, 1, 661805, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
