# Generated by Django 2.2.10 on 2020-10-23 00:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0004_auto_20201023_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 0, 57, 56, 344780, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
