# Generated by Django 2.2.10 on 2020-10-23 02:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls_app', '0006_auto_20201023_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='anonymous_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 2, 58, 43, 993233, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
