# Generated by Django 2.2.10 on 2020-10-23 09:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0008_auto_20201023_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='anonymous_user_id',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=200, verbose_name='Выбранный вариант ответа'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Количество голосов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 9, 27, 41, 711614, tzinfo=utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='registeredvote',
            name='anonymous_user_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='Айди анонимного пользователя'),
        ),
        migrations.AlterField(
            model_name='registeredvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
