# Generated by Django 2.2.10 on 2020-10-23 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0013_auto_20201023_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 9, 38, 21, 746441, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
