# Generated by Django 2.2.10 on 2020-10-28 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0017_auto_20201028_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 14, 2, 4, 688033, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
